version: 2
updates:
  # Note: We are not listing package-ecosystem: "github-actions". This causes
  # noise in all template instances. Instead dependabot.yml in scipp/copier_template
  # triggers updates of github-actions in the *template*. We then use `copier update`
  # in template instances.
  - package-ecosystem: "pip"
    directory: "/requirements"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "scipp"
        dependency-type: "direct"
